/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class ch_bfh_bachelor_ar_ArLib */

#ifndef _Included_ch_bfh_bachelor_ar_ArLib
#define _Included_ch_bfh_bachelor_ar_ArLib
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     ch_bfh_bachelor_ar_ArLib
 * Method:    initArLib
 * Signature: (IIII)V
 */
JNIEXPORT void JNICALL Java_ch_bfh_bachelor_ar_ArLib_initArLib
  (JNIEnv *, jclass, jint, jint, jint, jint);

/*
 * Class:     ch_bfh_bachelor_ar_ArLib
 * Method:    precessImage
 * Signature: ([B)V
 */
JNIEXPORT void JNICALL Java_ch_bfh_bachelor_ar_ArLib_precessImage
  (JNIEnv *, jclass, jbyteArray, jfloat, jfloat, jfloat);

#ifdef __cplusplus
}
#endif
#endif
